name: deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: |
        docker swarm init
        docker stack deploy -c docker-compose.yml mxs
    - name: Wait 90 secs to fully deploy
      run: sleep 90
    - name: maxctrl list servers
      run: |
        docker ps
        container_id=`docker ps | grep _maxscale | cut -f1 -d' ' `
        echo $container_id
        docker exec $container_id maxctrl list servers
